# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ff36334857cc3212433f852918a3ce122d4ca93a0cf662c8fae1c2dcb19a386c8b62ab9bde0cf45fc93161a4e6c8b889e131ac933b4ef2764f977972f2dd15

test:
  secret_key_base: 6d9b79aaf9d52e0e529a4a89d75bc32b3a3f60ff45a42fa6dd025cd0790c08e0859290897a0ce1d6e1768ba45fc9c5a6bf2415fea793a00715652dab7f96dd71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
